id: 78d14fcfaec44c6581675097f3acd7c3
title: Toh_846a-Threefold_Ritual-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-100-002
  eft-text-version: 1.1.5 2020
